---
apiVersion: v1
kind: Service
metadata:
  name: podtgresservice
  labels:
    name: podtgresservice
    author: empress
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgressapp
    author: empress
...

