---
apiVersion: v1
kind: Service
metadata:
  name: resultservice
  labels:
    name: resultservice
    author: empress
spec:
  type: loadbalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: resultapp
    author: empress
...