---
apiVersion: v1
kind: Pod
metadata:
  name: resultapp
  labels:
    name: resultapp
    author: empress
spec:
  containers:
    - name: myresult
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80


...