---
apiVersion: v1
kind: Service
metadata:
  name: votingservice
  labels:
    name: votingservice
    author: empress
spec:
  type: loadbalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: votingapp
    author: abc
...