---
apiVersion: v1
kind: Pod
metadata:
  name: votingapp
  labels:
    name: votingapp
    author: abc
spec:
  containers:
    - name: voting app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...